# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_delete_student.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(350, 40, 160, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.idnumForCourse = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.idnumForCourse.setObjectName("idnumForCourse")
        self.verticalLayout.addWidget(self.idnumForCourse)
        self.courseName = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.courseName.setObjectName("courseName")
        self.courseName.addItem("")
        self.courseName.addItem("")
        self.courseName.addItem("")
        self.courseName.addItem("")
        self.courseName.addItem("")
        self.courseName.addItem("")
        self.verticalLayout.addWidget(self.courseName)
        self.deleteSel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.deleteSel.setObjectName("deleteSel")
        self.verticalLayout.addWidget(self.deleteSel)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 140, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 260, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 180, 54, 12))
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(80, 40, 160, 451))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.idnumForStudent = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.idnumForStudent.setObjectName("idnumForStudent")
        self.verticalLayout_2.addWidget(self.idnumForStudent)
        self.deleteStudent = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.deleteStudent.setObjectName("deleteStudent")
        self.verticalLayout_2.addWidget(self.deleteStudent)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(280, -60, 20, 681))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.courseName.setItemText(0, _translate("MainWindow", "操作系统"))
        self.courseName.setItemText(1, _translate("MainWindow", "数据库系统"))
        self.courseName.setItemText(2, _translate("MainWindow", "生物化学"))
        self.courseName.setItemText(3, _translate("MainWindow", "计算机体系结构"))
        self.courseName.setItemText(4, _translate("MainWindow", "计算机网络"))
        self.courseName.setItemText(5, _translate("MainWindow", "遗传学"))
        self.deleteSel.setText(_translate("MainWindow", "删除选课"))
        self.label.setText(_translate("MainWindow", "学号"))
        self.label_2.setText(_translate("MainWindow", "课程名"))
        self.label_3.setText(_translate("MainWindow", "学号"))
        self.deleteStudent.setText(_translate("MainWindow", "删除学生"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
