# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(565, 443)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, 40, 160, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.makeViewBut = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.makeViewBut.setObjectName("makeViewBut")
        self.verticalLayout.addWidget(self.makeViewBut)
        self.makeIndexBut = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.makeIndexBut.setObjectName("makeIndexBut")
        self.verticalLayout.addWidget(self.makeIndexBut)
        self.insertBut = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.insertBut.setObjectName("insertBut")
        self.verticalLayout.addWidget(self.insertBut)
        self.deleteBut = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.deleteBut.setObjectName("deleteBut")
        self.verticalLayout.addWidget(self.deleteBut)
        self.queryBut = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.queryBut.setObjectName("queryBut")
        self.verticalLayout.addWidget(self.queryBut)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 10, 81, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 565, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.makeViewBut.setText(_translate("MainWindow", "创建视图"))
        self.makeIndexBut.setText(_translate("MainWindow", "创建索引"))
        self.insertBut.setText(_translate("MainWindow", "插入学生信息"))
        self.deleteBut.setText(_translate("MainWindow", "删除学生信息"))
        self.queryBut.setText(_translate("MainWindow", "查询学生信息"))
        self.label.setText(_translate("MainWindow", "学生信息管理"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
